#!/usr/bin/env bash

# vim-misc directory 
dir="$HOME/.vim/bundle/vim-misc"

if [[ -f $HOME/.vimrc ]]
then
    mv $HOME/.vimrc $HOME/.vimrc.backup
    echo '~/.vimrc was moved to ~/.vimrc.backup'
fi
echo "source $dir/vimrc" > ~/.vimrc

if [[ -f $HOME/.tmux.conf ]]
then
    mv $HOME/.tmux.conf $HOME/.tmux.conf.backup
    echo '~/.tmux.conf was moved to ~/.tmuf.conf.backup'
fi
echo "source $dir/tmux.conf" > ~/.tmux.conf

mkdir -p $HOME/.vim/backups
mkdir -p $HOME/.vim/sessions
mkdir -p $HOME/.vim/swap
mkdir -p $HOME/.vim/undo
mkdir -p $HOME/.vim/spell

echo 'open vim and run PluginInstall'
