#!/usr/bin/env bash

# vim-misc directory 
dir="source $(dirname "$(readlink -f "$0")")"

echo "source $dir/vimrc" >> ~/.vimrc
echo "source $dir/tmux.conf" >> ~/.tmux.conf

add_dir() { [[ ! -d $1 ]] && mkdir -p $1 }
add_dir $HOME/backups
add_dir $HOME/sessions
add_dir $HOME/swap
add_dir $HOME/undo
add_dir $HOME/spell
